### ISSUE TITLE
social icons on listing should be "share" links

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#39]
The social icons on the property listing page...

![Screen Shot 2022-10-12 at 10 43 47 AM](https://user-images.githubusercontent.com/2564452/195409025-e6ca8e7b-2b9b-4e08-b6fc-414867229111.png)

Should be "share" icons, facilitating a user's desire to share a listing on social media. Currently the icons are simply links to the client's social media profiles.

**Comment by emontes** [comment]
done

**Comment by figart** [comment]
good!
