### ISSUE TITLE
Listing page visual modification to property summary

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#40]
This section of the listing page...

![Screen Shot 2022-10-12 at 12 48 17 PM](https://user-images.githubusercontent.com/2564452/195412981-d4207419-0d10-4852-96a7-e8303df36c85.png)

- Make sure the font weight of county, acreage and price are "regular", or 400 (not 450 which I'm seeing now in inspector).
- Change these around to eliminate the colons (":") and to read like this: 

![Screen Shot 2022-10-12 at 12 47 49 PM](https://user-images.githubusercontent.com/2564452/195414571-bf2dcf55-bf57-412c-936e-9b16c5840bdc.png)

- Change line height for these three lines to 23px (I believe we're currently at 22px).

**Comment by emontes** [comment]
Solved

**Comment by figart** [comment]
excellent, thank you!
