### ISSUE TITLE
Specify target image for facebook and twitter

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#41]
When sharing listings to facebook/twitter, we need appropriate meta data on the page to allow platforms to identify the proper image to use. This would always be the first (main) image of the listing... the same one used on the listing card and the first in the gallery.

**Comment by emontes** [comment]
Done,

I changed the entire SEO component in general, it has some additional details that are subtle but will greatly improve SEO performance.

Also in the og:url I put the canonical address, if you look the url is Modal, however the link to share on facebook. It is the "not modal"

![image](https://user-images.githubusercontent.com/1318017/195722864-e736a41e-558a-4276-84c7-5794a3903819.png)

**Comment by emontes** [comment]
By the way, I am not seeing the latest changes that I have sent reflected in https://trs-development.gtsb.io/

I would need to see in the Gatsby cloud if there is no error when doing the build.

I've been looking at the Gatsby cloud and I only see the main branch. Maybe you have to give me access to the development branch?

**Comment by figart** [comment]
> I changed the entire SEO component in general, it has some additional details that are subtle but will greatly improve SEO performance.

super interested in the details here, Enrique. can you tell me more?

**Comment by figart** [comment]
> Also in the og:url I put the canonical address, if you look the url is Modal, however the link to share on facebook. It is the "not modal"

yes, this is ideal, thank you.

**Comment by figart** [comment]
Noting here that I can't see these changes myself yet... looks like it's not on live (which you basically said yourself). 

> By the way, I am not seeing the latest changes that I have sent reflected in https://trs-development.gtsb.io/

I'm looking into this now.

**Comment by figart** [comment]
I'm thinking now that the previous developer wasn't aware that you can change the branch that Gatsby Cloud uses, so he must have set up his own Gatsby Cloud account. I've changed our instance to use the development branch. It's building now... seeing lots of warnings, but no errors yet.

**Comment by emontes** [comment]
> 

In the SEO changes (hehe, alwayas an interesting topic), you can see the changes in this commit: 
https://github.com/digett-trs/trs/commit/877af258dfde94f87e2834a14ce36c1f0df24839

The interesting file changed is /src/components/seo.js.  basically in this part 

![image](https://user-images.githubusercontent.com/1318017/195741733-9084878a-5850-4f04-af9b-d28c2e2131f8.png)

In the final product the meta elements are almost the same but generated in a different way, in my opinion it's neater and easier to manage putting them this way.

An important thing is that now we can also have a "global" image for when any other page is shared, for example the home page. Please send me an image that we can use as "global share"

![image](https://user-images.githubusercontent.com/1318017/195742406-a251bd6d-0bf2-4819-b1ec-a788821ff42a.png)

For example, check on my website, I have an og:image that doesn't appear at all on my site, it only appears when shared on facebook, twitter, etc. and this same image is applied to the entire site (except the pages that have their own image defined to share, in our case the properties.)

**Comment by emontes** [comment]
> ah... error. check it out and let me know what you think.

I found and fixed the error, I have commented the solution here https://github.com/digett-trs/trs/issues/36#issuecomment-1278396522

For the moment is not the most elegant solution, but tomorrow I will work in a better one.   What is a fact is that we have to have the host name fixed.

By the way our development branch is now being deployed at https://trs.gatsbyjs.io/

I don't know what you think, but I like it that way. Maybe for later think about getting rid of the current "main" branch. We delete it and rename "development" as "main", think about it and then you tell me.

**Comment by figart** [comment]
> you can see the changes in this commit

Okay, I agree with you on this so far... these look like improvements to me. Thank you!

**Comment by figart** [comment]
> By the way our development branch is now being deployed at https://trs.gatsbyjs.io/

Yes, this is what I was telling you above where I said:

> I've changed our instance to use the development branch.

So I think we're all good here. 

> What is a fact is that we have to have the host name fixed.

I'm not sure what you're referring to specifically here, but I trust you'll take care of it. Should I close out this issue, then?

**Comment by emontes** [comment]
> I'm not sure what you're referring to specifically here,

I have explained it in more detail here https://github.com/digett-trs/trs/issues/36#issuecomment-1279212144 

And yes, you can close this issue, I saw that you opened another one specifically for the default image to share, so we can continue there if we need anything.
