### ISSUE TITLE
check "global share" image from site settings

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#42]

**Comment by figart** [comment]
@emontes I can't even remember you asking me for this, but hopefully you do. 😆

![Screen Shot 2022-10-24 at 11 03 41 AM](https://user-images.githubusercontent.com/2564452/197572699-68ba6d46-3da7-474d-bd17-8a6f2176beb8.png)

The attached should work as a global sharing image. But I'm wondering... is this something the client could change through Sanity? I think that would be ideal. Maybe accommodate this in the ["site settings" document](https://trs.sanity.studio/production/desk/siteSettings;settings)?

**Comment by emontes** [comment]
Now the global image for sharing is displaying (perhaps still not in production for the current error with algolia) 

![image](https://user-images.githubusercontent.com/1318017/198159353-9e22a944-eebc-48f2-8cb1-850823a4e7be.png)

The image is comming from Sanity / Site Settings / Global Share Image and the client can change whenever he wants to.

**Comment by figart** [comment]
Looks great!
