### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#43]
When I click on "Wolf Ranch" in the hero carousel I get a 404. I believe that either the link is being formed incorrectly, or that the property is no longer in Sanity (in which case it should not be in the carousel).

**Comment by emontes** [comment]
** I am going to use this comment for my personal thoughts, please don't waste your time reading it.

- Viewing this issue I notticed that under "Site Setting" in Sanity the Descriptions is missing, I putted there the description that we are using ing gatsby-config. (for testing purposes).  Note for developer:  Tere is a webhook that launches a buid in Gatsby cloud as soon as you publish a change in Sanity.

**** Spanish notes for Enrique (for not missing my thoughts in translation)
- En GraphQl hay una Tabla llamada allProperti ¿cuál es su fuente de datos? creo que es la que dice Marc de la American Asociation de algo
Los está tomando de  url: "https://mls-api-trfs.pantheonsite.io/rest/mls", con el plugin "gatsby-source-apiserver", de aquí hay 202 propiedades.

- en allSanityProperty sí aparecen listadas las 5 propiedades, sin embargo en el Sanity Studio solamente me aparece Wolf Ranch. ¿por qué?  (preguntarle a Mark).

```
allSanityProperty {
    nodes {
      propertyName
      slug {
        current
      }
    }
  }
```

- gatsby-source-sanity se llama en la linea 80 del gatsby-config y se supone que trabaje en ambiente "production"

**Comment by emontes** [comment]
I finally found the bug

Here in gatsby-node.js
![image](https://user-images.githubusercontent.com/1318017/197289699-2ae7fc29-5785-45cf-827c-d7986ed8d0c2.png)

We have this filter  filter: { _id: { regex: "/^(?!draft).*$/" } }

Regular Expressions (regexp) are always a very complicated topic. I don't 100% understand what this regex is doing. It is something like the property id does not contain "draft"

Analyzing the ids of the 5 properties, I found no differences in patterns, nor in the Wolf Ranch id. So I don't know why the regex was specifically blocking the Wolf Ranch id.

Finally the solution was to get rid of the regexp. But I would like to know (if there is still someone in the team involved in this area). What was that regex for?

**Comment by figart** [comment]
That regex was something that the previous contract came up with. I'm not sure why, though, as his task was to add a new boolean field to the Sanity properties allowing the client to select which properties get featured. I'm actually seeing some evidence of this in Sanity...

![Screen Shot 2022-10-23 at 9 05 19 PM](https://user-images.githubusercontent.com/2564452/197433661-d1d09c51-82a8-4128-8cda-17f7b4e18632.png)

... though I don't fully understand what's going on here. Maybe we need to have a conversation about this? And this brings up another topic that's been on my mind. Maybe we should look at merging with the main branch soon?

**Comment by figart** [comment]
> Finally the solution was to get rid of the regexp.

Then how are you selecting the properties for the carousel? Which properties get selected... what is the criteria?

**Comment by emontes** [comment]
At first glance I think it is taking them from Sanity, you have the following structure:
Base / Components / Property Carousel / homepage-property-carousel

I'm not sure because I still can't find the specific part where it does the connectivity. Do you think I'm on the right path? I mean does the client put the properties directly into Sanity (base/components/property Carousel) ?

**Comment by emontes** [comment]
So the data for the carousel is no longer being taken from the subject of "Featured" but is instead being taken directly from "homepage-property-carousel"

![image](https://user-images.githubusercontent.com/1318017/197570838-84fd7af5-261f-4349-a96e-2d086276d3dd.png)

I wanted to make sure that the regexp I removed didn't cause us problems, so yes, it had no reason to be.

**Comment by figart** [comment]
Data should not be coming from a separate Sanity doc type. That's how it was originally, but the client decided that he wanted to use the carousel to feature actual listings. So the requirement is to use a field in Sanity to indicate which properties should be featured in the carousel. Does this make sense? Judging from the screen shot of the error I added in a previous comment, it looks like this field had been added at some point. Let me know if we need to chat about this.

**Comment by emontes** [comment]
I think I understood the Idea
- Client is requesting a "Fetured" field for displaying the properties in the carousel
- I think currently the carousel is taken from "homepage-property-carousel, if that is the case we need to do it as the client want and add a field "featured" in properties table (I also think that it is the most orthodox thing to avoid duplicating information.)
- At some point the field existed, then I have to find out whre and how to reactivate it (or in its case add it).

Am I right?

**Comment by figart** [comment]
Correct. I wonder if you wouldn't find some clues in the "develop-carousel" branch.

**Comment by emontes** [comment]
### Notes for developer
The change for using propertyCarouse as independent Table (schema) was made in this commit
https://github.com/digett-trs/trs/commit/741b090965e1cf58d48bdada0207270e6423d0cf

**Comment by emontes** [comment]
After all the "draft" regexp is necessary, what was happening with the property not displaying was that it was indeed in draft mode. I have to put it back.

**Comment by figart** [comment]
Okay, good find.

**Comment by emontes** [comment]
Yes, it can be closed
