### ISSUE TITLE
merging branches

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#44]
Any reason that we shouldn't try to merge the development branch with main?

**Comment by emontes** [comment]
I have merged the development branch in to main. Apparently there was no problem.

Where is the main branch being deployed to?

**Comment by figart** [comment]
To deploy main, I simply had to change the branch within the Gatsby console. I'm pretty sure you have access to do this, too, [here](https://www.gatsbyjs.com/dashboard/9b01b357-c30e-4fbe-9cc2-0624b8673e74/sites/d61d5649-9d2e-49c5-a6e4-38b80bdc46f1/settings/general#site-details). 

![Screenshot 2022-10-30 at 1 46 03 PM](https://user-images.githubusercontent.com/2564452/198896073-9d0185d7-753d-4957-8a61-f8283d138627.png)

I've changed it to "main", but it can be changed back any time. I noticed the "partner" section disappeared when I changed it to main, so I'm assuming that still needs to be merged in.

I'm pretty sure you can generate a build of a different branch just by creating a pull request in github. If this is not the case, or if you don't see this happening automatically, then let's get @alexanderfountain to help us with this.
