### ISSUE TITLE
adjust agent contact info display

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#46]
On the listing page, when the info column narrows the contact info wraps like this:

![Screen Shot 2022-10-18 at 1 18 28 PM](https://user-images.githubusercontent.com/2564452/196512374-36fc4886-cb4e-4531-9938-543cf78e4483.png)

Rather than have the agent name (and email icon) wrap, let's keep them on the one line and have the phone number move to under the agent name when the column content gets below, say, 384 pixels. Or let me know if you think there's a better way to handle this.

**Comment by emontes** [comment]
** Notes for Developer Only
- Site is using Material UI Framework

**Comment by figart** [comment]
I like what you've done here, @emontes. You good with me closing?

**Comment by emontes** [comment]
@figart yes please, close it
