### ISSUE TITLE
add featured images to Sanity properties

### ISSUE THREAD

**Issue by emontes** [digett-trs/trs#51]
In Sanity we added 2 new properties:
- Saline Creek Ranch
- Honew Creek Ranch

Saline Creek Ranch is not been displayed on development, and aparently is making some conflict in build.
``` 
Note: The reason why it is not deployed in development is because the properties are being 
taken directly from the algolia index (not from Graphql), so having an error in algolia will not deploy 
it in development or production.
```

Algolia is saying:
failed to index to Algolia Record at the position 0 objectID=-fbdb1b2a-8fd4-5677-86db-0aeca3a55e0c is too big size=119914/100000 bytes.

After some testings unpublishing and publishing other properties, I have no doubt now that the problem is something with the Saline Creek Ranch property.

I'm wondering if the property does not have too much photos.

**Comment by emontes** [comment]
The problem comes from the size of the registry that is allowed by algolia.

Gatsby (GraphQl) is correctly fetching property data.

![image](https://user-images.githubusercontent.com/1318017/198002032-32d06f42-a323-4057-add1-48af06d35b25.png)

The problem comes at the end of the building proccess when Algolia try to make it's index.

Perhaps the problem is the number of pictures in the property.  

I'm not sure that if I delete the Sanity photos I'll be able to get them back later. 

Could you please help me with that @figart ? I mean try to delete some pictures.

**Comment by figart** [comment]
Okay, nice work on figuring this out so far. Yeah, unfortunately my client is not going to accept "fewer photos" as an option. I wonder if another idea—although not without significant impact, I'm sure—might be to create a separate field for the first photo... we could call it "featured photo" or something like that. And then we wouldn't have to index the other photos at all? Would that be an option?

**Comment by emontes** [comment]
Yes the proposal is to make an aditional "FeaturedPhoto" field  (that was what I meant by "make a new field for the facet"). 

In this way algolia will only index that photo.   In the long term it will be much better because algolia index size will be significantly reduce and with this we will save lot of costs with algolia (server time, bandwidth, etc).  And I am almost sure that we will also decrease the build times for Gatsby.

The inconvenience that I mentioned is that I am going to have to change several parts of the program (and that is going to take time). At first glance the property display cards, and I don't know if anything else comes up in the process. But finally I think it is the best solution.

So let me know if you agree with the change, which in summary is going to be:
1.- Add new FeaturedPhoto field to properties.
2.- Make algolia to index only the FeaturedPhoto
3.- Fix possible issues with properties display of the FeaturedPhoto.

**Comment by figart** [comment]
Let me just run this by Alexander to see if he agrees. Should be able to talk to him within an hour or so.

**Comment by figart** [comment]
Alexander also says, "Enrique might need me to add a field to the api with just 1 image as the value. I don't think you can query graphql for the first item in field array."  

Does this sound correct to you? If so I'll get Alexander to add it... should be a quick fix. Let me know! :-)

**Comment by emontes** [comment]
Yes, sounds perfect.  Regarding to add the field I will try to add it from the Sanity studio, also I need  to add a field for the global share image in "Site Settings".  

If I run into too many problems or if I see that it is going to take me a long time to do it, then yes I would ask Alex for his help. But I think I can do it, I'm going to try with the Global Share image field first.

**Comment by figart** [comment]
Aha... I understand that you will need to add the field in Sanity, but that
includes only the Sanity data. Will you not want/need to do the same for
the data coming from Drupal... to be able to select just the cover image?

**Comment by emontes** [comment]
That is true, it will be necessary to import the covers for all the properties, so yes, please, if Alex can help me with that, that would be perfect.

I already aded the following field to Sanity:
```
{
      title: 'Property Featured Image',
      name: 'propertyFeaturedImage',
      type: 'image',
    },
```

This propertyFeaturedImage field was actually already added by the previous developer, remember the carousel thing? this was one of the fields he didn't send to Sanity (they stayed on his local computer).

What I do not know how to do is import the data from drupal.

**Comment by emontes** [comment]
It's done, now algolia is indexing only the propertyFeaturedImage instead of all property's images.

Btw in the Sanity properties the only one wich has a Featured Image is Wolf Ranch.

**Comment by figart** [comment]
> It's done

Congratulations, that's a BIG fix!

> in the Sanity properties the only one wich has a Featured Image is Wolf Ranch

Okay, @emontes, sounds like you want me to get those others added... no problem, I'll take care of them.

**Comment by figart** [comment]
renaming and reassigning this issue to myself

**Comment by emontes** [comment]
I already put the images in sanity, the hard part is finding the images in the sanity browser, but it's done.

I know you had "self-assigned" this task, but I needed to avoid error messages (of which there are many) to continue fixing the Search Clear issues.

Also you can close this issue

**Comment by figart** [comment]
@emontes thanks for adding those images. 

I feel like we should move the "property featured image" field up nearer to the top of the add/edit page in Sanity. Could we put it under the "Property Summary" field?

And just a  couple questions here:
- Is there a way to eliminate the errors even when a featured image is empty/null? Can we add error handling to accommodate? 
- Are we using the featured image in the carousel, too? I'm not sure whether or not it's necessary... mostly curious.

**Comment by emontes** [comment]
> Could we put it under the "Property Summary" field?

Done

> Is there a way to eliminate the errors even when a featured image is empty/null? Can we add error handling to accommodate?

I had already implemented something to avoid crashing when there is no image. In fact, it doesn't display anything.
If you find any errors that I haven't seen, please let me know.

>Are we using the featured image in the carousel, too?

No

**Comment by figart** [comment]
@emontes Looks great, thank you!
