### ISSUE TITLE
Error when filtering by Kendall County

### ISSUE THREAD

**Issue by emontes** [digett-trs/trs#53]
When we select this county we got the following error

![image](https://user-images.githubusercontent.com/1318017/198856866-b13339f9-7417-4f06-b0c7-f7a877fa4a95.png)

This error is only with this County what makes me think there is an error in one of the properties.

**Comment by figart** [comment]
I noticed that Kendall was not an entry in Sanity and thought maybe that was causing the issue. But even after [I added it](https://trs.sanity.studio/production/desk/propertyAttributes;county;33d48723-6460-4683-abe4-d763f17c63eb), the error still occurred. I noticed that If I choose "Gillespie" first, and then add "Kendall" to the filter, it seems to work (and this was true even before I added "Kendall" to Sanity), but as soon as I remove Gillespie, the page breaks (white screen). I also found that if I click the "View More Properties" button enough times, this also breaks the page. I made a separate issue for this.  #55

**Comment by figart** [comment]
@emontes Would you mind describing what the problem was here? I think we discussed but I can't remember.

**Comment by emontes** [comment]
I was almost sure that I have commented the whole problem,  perhaps I forgot to push the green "comment" button.  Sorry for that. 

Well the problem was with some properties (the kind of properties that are not in Sanity).  Some of the has a Gatsby image indexed in algolia, and some of them has direct the url of the picture. 

Then the solution to avoid system crashing was to display in a different way the image if is Gatsby Image and if is Regular image.

In This commit https://github.com/digett-trs/trs/commit/9903cfd31bf0e7cf82552066ae8b6929f7d69d6f

In the propertyTeaser.js file is the main solution.

**Comment by digett-trs** [comment]
Got it, makes sense.  To clarify, though, are we using the gatsby-image plugin for all of the images? And if not, should we be? I'm pretty sure that has some performance advantages.

**Comment by figart** [comment]
@emontes can you give me an example or two of where we are _not_ using it?

**Comment by emontes** [comment]
For example if you Filter Kendall County,
46 FM 1621 has a direct image (not Gatsby)

**Comment by figart** [comment]
is there a way for me to see this in the browser using the inspector?

**Comment by emontes** [comment]
![image](https://user-images.githubusercontent.com/1318017/199321568-f34c311d-64f1-4e9c-92b2-c54961367228.png)
This is inspecting the image of 46 FM, note the <img src ... tag

**Comment by emontes** [comment]
![image](https://user-images.githubusercontent.com/1318017/199321847-66b2b1e7-cb1e-4aed-9013-71896a89f482.png)
And this is inspecting (on the same page) the Brand RD property, note the <picture tag, that cames from gatsby-image-plugin

**Comment by figart** [comment]
aha... thank you!

**Comment by figart** [comment]
Looking at these I'm uncovering some other issues. Will make a couple new issues. They may be trivial, but I can't tell for sure.
