### ISSUE TITLE
Add Photos field to Team Members in Sanity and Display them.

### ISSUE THREAD

**Issue by emontes** [digett-trs/trs#57]
That was already done in the following commit [fb2d3c1](https://github.com/digett-trs/trs/pull/32/commits/fb2d3c1a78f884f03b279646528984f115f21084)

Then Our mission is to take that cnages and integrate it with the development branch.

Also we need to change some field labels as commented here:
https://github.com/digett-trs/trs/pull/32#issuecomment-1297782182

**Comment by emontes** [comment]
Solved, now the extra pictures are displaying and the Member labels has been changed.

The commands to send structure changes in sanity are:

```
sanity build
sanity deploy
sanity graphql deploy
```
(Sorry for being so redundant with this commands but I can't memorize them, and then I leave them for future reference

**Comment by digett-sim** [comment]
> now the extra pictures are displaying

Where should I be looking to see these, @emontes ?

**Comment by emontes** [comment]
You can see an example here https://trs-development12017.gtsb.io/our-team/ken-hoerster

An the pull request is https://github.com/digett-trs/trs/pull/58

**Comment by figart** [comment]
How would I know that without asking you, @emontes? In the future would it be possible for you to link the issue and the pull request?

**Comment by figart** [comment]
Ahh... nevermind... I can see this now in the PR... my bad. Although it _would_ be great if you could link to the PR from the issue as well. Thank you! By the way, this looks great! Closing.
