### ISSUE TITLE
going from two- to one-column layout causes re-sort

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#59]
When I look at listings on desktop at a width that shows either 2 or 3 columns everything looks fine. But if I size the viewport down to force one column (or if I view the site on mobile) the listings get re-sorted. Notice how the L5 ranch (_first_ in 2- or 3-column view) goes down to the _fifth_ position in a single column view.

**Comment by emontes** [comment]
The css for that displaying is in scss/pages/layout.scss

.ais-InfiniteHits-list

for displaying the properties we are using 
const CustomInfiniteHits = connectInfiniteHits(InfiniteHits)

In lne 80 of index.js aparently the properties in mobile uses diferent layer not necesary from flex-box rules in .ais-InfiniteHits-list

**Comment by emontes** [comment]
I'm not so sure now that it's a bug. Rather it is an algolia behavior. 

As soon as the Filter Container is opened, it applies the sort defined in
![image](https://user-images.githubusercontent.com/1318017/200624805-683ebfca-ed30-4a62-ba6d-12aebb5fc70c.png)

This is sorted by price descending.

As soon as you close the Filter Container the properties are displayed in their natural order. 

The part that defines the open / close behaviour is this
![image](https://user-images.githubusercontent.com/1318017/200674821-23befe33-8ba1-4f2f-a202-4cf6dd48f306.png)


I have not found how to send algolia to start directly ordered by price.

**Comment by figart** [comment]
@emontes, do we need to have Alexander look at this one?

**Comment by emontes** [comment]
Solved on https://github.com/digett-trs/trs/commit/b2ee330f7934406cf29c5ec16c1acf56b5fdab2b
