### ISSUE TITLE
Listing cards have multiple picture tags

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#60]
I honestly don't know for sure there's a problem here, but it seems odd that each listing card has two (2) `<picture>` tags. Shouldn't there be only one?

**Comment by figart** [comment]
I thought it was in all the properties, but looking more closely it looks like it's on all the imported listings. "Alternate 90", for example: 

![Screenshot 2022-11-01 at 4 12 01 PM](https://user-images.githubusercontent.com/2564452/199342683-211c04fa-abc5-435c-a25e-a81f9d416198.png)

**Comment by emontes** [comment]
The first < picture > that you see is for the map-pin image 
![image](https://user-images.githubusercontent.com/1318017/199363454-6b3d746b-2280-41e4-bbf9-34f4bdd33c82.png)

You are right, it should be in all properties.

**Comment by figart** [comment]
> You are right, it should be in all properties.

Not sure if I understand this. Should we keep this issue open for some reason?

**Comment by emontes** [comment]
I was telling you that the <picture> tab appears twice in each property because one is used for the map-pin image and the other for the Gatsby Image. So there is no problem that it appears 2 times.

There is no need to keep this ticket open as everything seems to be working fine.

**Comment by figart** [comment]
Okay, got it, thank you @emontes!
