### ISSUE TITLE
hero text overlay transition not in sync

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#61]
Note this screenshot, with the descriptor text overlay appearing (1) over the hero image _and_ (2) below the image. 

![Screenshot 2022-11-09 at 8 44 55 AM](https://user-images.githubusercontent.com/2564452/200861416-e0bf96f3-dcac-4ff2-9996-e4202d93f755.png)

The text overlay should disappear at the same time the text appears below the photo.

**Comment by emontes** [comment]
Fixed on https://github.com/digett-trs/trs/commit/e6b997285b6eae756f8b64c38d9b2e2dad537cb6
