### ISSUE TITLE
property listing page should show all contacts associated with the listing

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#73]
Looking at [Colorado Bend River Ranch](https://trs.gatsbyjs.io/property/burnet-county-colorado-bend-river-ranch-nw-burnet-ranch-for-sale?isModal=true). It's showing Griffin, but not Ken. Here it is [in Sanity](https://trs.sanity.studio/production/desk/properties;f3eca23e-a65b-45b4-a4c3-2122b20fb789).

**Comment by alexander-digett** [comment]
Ready for review.
https://trs-development65648.gtsb.io/

**Comment by figart** [comment]
Hmmm... I'm not seeing the agent phone numbers. @alexander-digett

**Comment by figart** [comment]
okay... _now_ they're showing up... thank you!
