### ISSUE TITLE
property cards getting cut off on mobile

### ISSUE THREAD

**Issue by figart** [digett-trs/trs#76]
Note right side:

![Selling Quality Ranches Throughout Texas  Texas… png](https://user-images.githubusercontent.com/2564452/201184927-9aeac2df-2e8f-4348-bb85-bb72e3d9d281.png)

**Comment by alexander-digett** [comment]
ready for review:
https://trs-development65648.gtsb.io/

**Comment by figart** [comment]
looks good!
